"""add_trace_id_to_outbox

Revision ID: e6cb22fbc686
Revises: b2ee89bbb01f
Create Date: 2026-06-15 15:42:00.684675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cb22fbc686'
down_revision: Union[str, Sequence[str], None] = 'b2ee89bbb01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('trace_id', sa.String(length=36), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'trace_id')
    # ### end Alembic commands ###
